add BinarySearchJava
ddKirill/programm-start pull request #1
Opened 2020-10-04 18:03 UTC by ddKirill

Реализация алгоритма Бинарного поиска

2020-10-04 18:15 UTC, glockbender requested changes

2020-10-04 18:15 UTC, glockbender commented on src/com/company/task1/BinarySearchJava.java
> +     int a = 0;
Называй переменные осмысленно

2020-10-04 18:15 UTC, glockbender commented on src/com/company/task1/BinarySearchJava.java
> +     int b = array.length -1;
см. выше

2020-10-04 18:15 UTC, glockbender commented on src/com/company/task1/BinarySearchJava.java
> +         //индекс среднего элемента
комментарий желательно над а не под строкой

2020-10-04 18:15 UTC, glockbender commented on src/com/company/task1/BinarySearchJava.java
> +         if(a > b){
Возможно здесь лучше написать >=

2020-10-04 18:15 UTC, glockbender commented on src/com/company/task1/Main.java
> +        int[] name = new int[]{1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
как-то не оч логично названо

2020-10-04 18:15 UTC, glockbender commented on src/com/company/task1/Main.java
> +        instance.search(name, 2);
boolean result = instance.search(name, 2)
sout(result)

2020-10-04 18:16 UTC, ddKirill commented on src/com/company/task1/Main.java
> +        instance.search(name, 2);
Сделал

2020-10-04 18:19 UTC, glockbender approved these changes

2020-10-04 18:20 UTC, glockbender requested changes
жду фиксы

2021-03-26 13:49 UTC, glockbender reviewed
Хорош. Правильно делаешь, что начинаешь с более простых сортировок

2021-04-22 19:15 UTC, merged